version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - './frontend/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - client

  frontend:
    image: node:9.3
    volumes:
      - './frontend/:/code'
    command: 'yarn watch'
    environment:
      - NODE_ENV=development
    ports:
      - '8001:8001'
