version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - './frontend/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - frontend

  frontend:
    build: './frontend'
    volumes:
      - './frontend/:/code'
    command: 'yarn start'
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
