version: 2
jobs:
  build:
    docker:
      - image: node:9.3
    steps:
      - checkout
      - run:
          name: Start at
          command: date
      - run:
          name: Tests should pass
          command: yarn test
      - run:
          name: Done at
          command: date
